version: '3.8'
services:
  web:
    build: .
    volumes:
      - .:/app
      - ./app/static/uploads:/app/app/static/uploads
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
    env_file:
      - .env

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ultraman_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
